// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from define_device_type.djinni

#import <Foundation/Foundation.h>

/**设备主类型 */
typedef NS_ENUM(NSInteger, GLDeviceMainType)
{
    /**联网主设备 */
    GLDeviceMainTypeGeeklinkDev,
    /**马库设备 */
    GLDeviceMainTypeDatabaseDev,
    /**自定义设备 */
    GLDeviceMainTypeCustomDev,
};
