// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from device_single.djinni

#import <Foundation/Foundation.h>

/**消毒定时记录 启动和取消当记录才有，其他没有 */
typedef NS_ENUM(NSInteger, GLDisinfectionOperationType)
{
    /**手动操作 */
    GLDisinfectionOperationTypeOperator,
    /**定时启动 */
    GLDisinfectionOperationTypeTimer,
    /**app操作 */
    GLDisinfectionOperationTypeApp,
    /**固件自动操作 */
    GLDisinfectionOperationTypeHardware,
};
