// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from device_single.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, GLDisinfectionRecordType)
{
    /**手动操作 */
    GLDisinfectionRecordTypeOperation,
    /**消毒结束 */
    GLDisinfectionRecordTypeEnd,
    /**消毒暂停 */
    GLDisinfectionRecordTypePause,
    /**恢复 */
    GLDisinfectionRecordTypeRestore,
    /** 取消消毒 */
    GLDisinfectionRecordTypeCancel,
    /**童锁禁止手动消毒 */
    GLDisinfectionRecordTypeChildLock,
};
