// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from define_device_type.djinni

#import <Foundation/Foundation.h>

/**
 *码库设备类型
 *STB 机顶盒0x02
 *STB 机顶盒
 *Fan 风扇
 *Air_Purifier 空气净化器
 *IPTV 安卓电视/盒子
 *Projector 投影仪
 */
typedef NS_ENUM(NSInteger, GLDatabaseDevType)
{
    /**AC 空调 */
    GLDatabaseDevTypeAC,
    /**TV 电视 */
    GLDatabaseDevTypeTV,
    /**STB 机顶盒 */
    GLDatabaseDevTypeSTB,
    /**STB 安卓电视 */
    GLDatabaseDevTypeIPTV,
};
