// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from define_device_type.djinni

#import <Foundation/Foundation.h>

/**
 * openSDKSamrPi 0x20开发SDK小pi
 * openSDK_uv_disinfection 0x22开放SDK紫外线消毒灯
 */
typedef NS_ENUM(NSInteger, GLGeeklinkDevType)
{
    GLGeeklinkDevTypeSmartPi,
    GLGeeklinkDevTypeDisinfectionLamp,
};
